plugin/dnstap: shadow some constants
This is needed to not reference a vendored package so out-of-tree
plugins don't get type errors when referencing this code, like:

../../miekg/forward/dnstap.go:27:16: cannot use "github.com/dnstap/golang-dnstap".SocketProtocol_UDP (type "github.com/dnstap/golang-dnstap".SocketProtocol) as type "github.com/coredns/coredns/vendor/github.com/dnstap/golang-dnstap".SocketProtocol in assignment
../../miekg/forward/dnstap.go:28:5: undefined: t
../../miekg/forward/dnstap.go:29:17: cannot use "github.com/dnstap/golang-dnstap".SocketProtocol_TCP (type "github.com/dnstap/golang-dnstap".SocketProtocol) as type "github.com/coredns/coredns/vendor/github.com/dnstap/golang-dnstap".SocketProtocol in assignment
../../miekg/forward/dnstap.go:36:46: cannot use "github.com/dnstap/golang-dnstap".Message_FORWARDER_QUERY (type "github.com/dnstap/golang-dnstap".Message_Type) as type "github.com/coredns/coredns/vendor/github.com/dnstap/golang-dnstap".Message_Type in argument to b.Data.ToOutsideQuery
../../miekg/forward/dnstap.go:46:47: cannot use "github.com/dnstap/golang-dnstap".Message_FORWARDER_RESPONSE (type "github.com/dnstap/golang-dnstap".Message_Type) as type "github.com/coredns/coredns/vendor/github.com/dnstap/golang-dnstap".Message_Type in argument to b.Data.ToOutsideResponse

Also had to rename them in CamelCase to make golint happy.